version: "3.7"
# https://docs.docker.com/docker-for-mac/osxfs/
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    volumes:
    - postgres:/var/lib/postgresql/data

  my_service:
    container_name: my-service
    build: .
    entrypoint: bundle exec server.rb
    depends_on:
    - db
    volumes:
    - bundle:/usr/local/bundle
    ports:
    - 50052:50052

  bundle:
    build: .
    entrypoint: bundle
    command: check
    volumes:
    - bundle:/usr/local/bundle

  rspec:
    build: .
    entrypoint: bundle exec rspec
    command: --version
    depends_on:
    - db
    volumes:
    - bundle:/usr/local/bundle

  protoc:
    build: .
    entrypoint: bundle exec grpc_tools_ruby_protoc
    command: -I ../protos --ruby_out=./lib --grpc_out=./lib ../protos/my_service.proto
    volumes:
    - bundle:/usr/local/bundle
    - ../protos:/usr/src/protos

volumes:
  postgres: {}
  bundle: {}
